/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\kiryu\OneDrive\Desktop\Private\3dmodel-configurator\public\models\chair.gltf -t 
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Chair: THREE.Mesh
    Cushion: THREE.Mesh
    Legs1: THREE.Mesh
    Legs2: THREE.Mesh
  }
  materials: {
    Chair: THREE.MeshStandardMaterial
    Cushion: THREE.MeshStandardMaterial
    Legs: THREE.MeshStandardMaterial
  }
}

const Chair = (props: JSX.IntrinsicElements['group'])=> {
  const { nodes, materials } = useGLTF('/chair.gltf') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair.geometry} material={materials.Chair} />
      <mesh geometry={nodes.Cushion.geometry} material={materials.Cushion} position={[0, 0.064, 0.045]} />
      <mesh geometry={nodes.Legs1.geometry} material={materials.Legs} />
      <mesh geometry={nodes.Legs2.geometry} material={materials.Legs} />
    </group>
  )
}
export default Chair;

useGLTF.preload('/chair.gltf');

