/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\kiryu\OneDrive\Desktop\Private\3dmodel-configurator\public\models\shoe.glb -t
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useAtomValue } from 'jotai'
import { shoeConfigAtom } from '@/atoms/shoe'

type GLTFResult = GLTF & {
  nodes: {
    shoe: THREE.Mesh
    shoe_1: THREE.Mesh
    shoe_2: THREE.Mesh
    shoe_3: THREE.Mesh
    shoe_4: THREE.Mesh
    shoe_5: THREE.Mesh
    shoe_6: THREE.Mesh
    shoe_7: THREE.Mesh
  }
  materials: {
    laces: THREE.MeshStandardMaterial
    mesh: THREE.MeshStandardMaterial
    caps: THREE.MeshStandardMaterial
    inner: THREE.MeshStandardMaterial
    sole: THREE.MeshStandardMaterial
    stripes: THREE.MeshStandardMaterial
    band: THREE.MeshStandardMaterial
    patch: THREE.MeshStandardMaterial
  }
}

const Shoe = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } =
    useGLTF('/models/shoe.glb') as unknown as GLTFResult

  const shoeConfig = useAtomValue(shoeConfigAtom)

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shoe.geometry}>
        <meshStandardMaterial
          {...materials.laces}
          color={shoeConfig.laces.color}
        />
      </mesh>

      <mesh geometry={nodes.shoe_1.geometry}>
        <meshStandardMaterial
          {...materials.mesh}
          color={shoeConfig.mesh.color}
        />
      </mesh>

      <mesh geometry={nodes.shoe_2.geometry}>
        <meshStandardMaterial
          {...materials.caps}
          color={shoeConfig.caps.color}
        />
      </mesh>

      <mesh geometry={nodes.shoe_3.geometry}>
        <meshStandardMaterial
          {...materials.inner}
          color={shoeConfig.inner.color}
        />
      </mesh>

      <mesh geometry={nodes.shoe_4.geometry}>
        <meshStandardMaterial
          {...materials.sole}
          color={shoeConfig.sole.color}
        />
      </mesh>

      <mesh geometry={nodes.shoe_5.geometry}>
        <meshStandardMaterial
          {...materials.stripes}
          color={shoeConfig.stripes.color}
        />
      </mesh>

      <mesh geometry={nodes.shoe_6.geometry}>
        <meshStandardMaterial
          {...materials.band}
          color={shoeConfig.band.color}
        />
      </mesh>

      <mesh geometry={nodes.shoe_7.geometry}>
        <meshStandardMaterial
          {...materials.patch}
          color={shoeConfig.patch.color}
        />
      </mesh>
    </group>
  )
}

export default Shoe
useGLTF.preload('/models/shoe.glb');